name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mondli24 }}
          password: ${{ secrets.Mshiki@98 }}

      - name: Build Docker image
        run: |
          docker build -t yourusername/sample-app .
          docker tag yourusername/sample-app yourusername/sample-app:${GITHUB_SHA}

      - name: Push Docker image to Docker Hub
        run: |
          docker push yourusername/sample-app
          docker push yourusername/sample-app:${GITHUB_SHA}

